### ISSUE TITLE
Reason behind the recommended entry points

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-rs#3]
[1.3.7 Application Entry Points](https://github.com/FamilySearch/gedcomx-rs/blob/master/specifications/rs-specification.md#137-application-entry-points):

> Use of the Collections, Collection, Person, and Source Description application states is RECOMMENDED as entry points.

Does this statement need a reason to support it? Collections, Collection, and Person are fairly obvious but Source Description isn't so obvious. At least to me.

**Comment by justincy** [comment]
I think you could argue that Agent or Person Search Results are useful entry points, but we don't want the recommended list to be too large.

Maybe just say

> It is RECOMMENDED the entry points include at least Collections, Collection, and Person.

**Comment by stoicflame** [comment]
I like that. Fixed at 4d8d955.
