### ISSUE TITLE
Authentication and authorization links

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-rs#4]
[9. Authentication and Authorization](https://github.com/FamilySearch/gedcomx-rs/blob/master/specifications/rs-specification.md#9-authentication-and-authorization)

> A server MAY require authorization to access certain application states. Authentication and authorization are outside the scope of this specification. OAuth 2 as specified by RFC 6749 is RECOMMENDED as an authentication mechanism.

However three states have OAuth2 links listed as valid transitions. It seems that any links to authentication and authorization resources ought to be implementation-specific extensions as opposed to being in the gedcomx-rs spec itself.

Can application states be extended?

**Comment by stoicflame** [comment]
> Can application states be extended?

Sure.

> It seems that any links to authentication and authorization resources ought to be implementation-specific extensions as opposed to being in the gedcomx-rs spec itself.

Maybe.

The thought was that these particular links were important enough that they should be mentioned explicitly in the spec. Also, the URIs being used as link rels to those resources aren't codified by any other spec (that I could find), so we had to be explicit about it.
